[package]
name = "cairo_circuits"
version = "0.1.0"
edition = "2025_12"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[executable]

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.15.0"
cairo_binary_merkle_root = { git = "https://github.com/vplasencia/cairo-binary-merkle-root" }

[dev-dependencies]
cairo_test = "2.14.0"
